"""
CB-prefixed instruction handlers for Game Boy CPU.

The 0xCB prefix accesses a second 256-opcode table with bit manipulation,
shift, rotate, and swap operations on all 8 targets: B, C, D, E, H, L, (HL), A.

All 256 opcodes are dispatched through 11 handler functions using operand
info pre-fetched by the run() loop. The dispatch table is generated by
build_cb_dispatch().
"""


def _read_target(cpu, operand):
    """Read value from a CB target (register or memory at HL)."""
    if operand["immediate"]:
        return cpu.get_register(operand["name"])
    else:
        return cpu.memory.get_value(cpu.get_register("HL"))


def _write_target(cpu, operand, value):
    """Write value to a CB target (register or memory at HL)."""
    if operand["immediate"]:
        cpu.set_register(operand["name"], value)
    else:
        cpu.memory.set_value(cpu.get_register("HL"), value)


# --- Rotate operations ---

def cb_rlc(cpu, opcode_info):
    """RLC - Rotate left circular. Bit 7 goes to carry and bit 0."""
    operand = cpu.operand_values[0]
    value = _read_target(cpu, operand)
    carry = (value >> 7) & 1
    result = ((value << 1) | carry) & 0xFF
    _write_target(cpu, operand, result)
    cpu.set_flag('Z', result == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', False)
    cpu.set_flag('C', carry == 1)
    return opcode_info['cycles'][0]


def cb_rrc(cpu, opcode_info):
    """RRC - Rotate right circular. Bit 0 goes to carry and bit 7."""
    operand = cpu.operand_values[0]
    value = _read_target(cpu, operand)
    carry = value & 1
    result = ((value >> 1) | (carry << 7)) & 0xFF
    _write_target(cpu, operand, result)
    cpu.set_flag('Z', result == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', False)
    cpu.set_flag('C', carry == 1)
    return opcode_info['cycles'][0]


def cb_rl(cpu, opcode_info):
    """RL - Rotate left through carry. Old carry goes to bit 0."""
    operand = cpu.operand_values[0]
    value = _read_target(cpu, operand)
    old_carry = 1 if cpu.get_flag('C') else 0
    new_carry = (value >> 7) & 1
    result = ((value << 1) | old_carry) & 0xFF
    _write_target(cpu, operand, result)
    cpu.set_flag('Z', result == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', False)
    cpu.set_flag('C', new_carry == 1)
    return opcode_info['cycles'][0]


def cb_rr(cpu, opcode_info):
    """RR - Rotate right through carry. Old carry goes to bit 7."""
    operand = cpu.operand_values[0]
    value = _read_target(cpu, operand)
    old_carry = 1 if cpu.get_flag('C') else 0
    new_carry = value & 1
    result = ((value >> 1) | (old_carry << 7)) & 0xFF
    _write_target(cpu, operand, result)
    cpu.set_flag('Z', result == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', False)
    cpu.set_flag('C', new_carry == 1)
    return opcode_info['cycles'][0]


# --- Shift operations ---

def cb_sla(cpu, opcode_info):
    """SLA - Shift left arithmetic. Bit 7 goes to carry, 0 into bit 0."""
    operand = cpu.operand_values[0]
    value = _read_target(cpu, operand)
    carry = (value >> 7) & 1
    result = (value << 1) & 0xFF
    _write_target(cpu, operand, result)
    cpu.set_flag('Z', result == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', False)
    cpu.set_flag('C', carry == 1)
    return opcode_info['cycles'][0]


def cb_sra(cpu, opcode_info):
    """SRA - Shift right arithmetic. Bit 0 goes to carry, bit 7 preserved."""
    operand = cpu.operand_values[0]
    value = _read_target(cpu, operand)
    carry = value & 1
    result = ((value >> 1) | (value & 0x80)) & 0xFF
    _write_target(cpu, operand, result)
    cpu.set_flag('Z', result == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', False)
    cpu.set_flag('C', carry == 1)
    return opcode_info['cycles'][0]


def cb_srl(cpu, opcode_info):
    """SRL - Shift right logical. Bit 0 goes to carry, 0 into bit 7."""
    operand = cpu.operand_values[0]
    value = _read_target(cpu, operand)
    carry = value & 1
    result = (value >> 1) & 0xFF
    _write_target(cpu, operand, result)
    cpu.set_flag('Z', result == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', False)
    cpu.set_flag('C', carry == 1)
    return opcode_info['cycles'][0]


# --- Swap ---

def cb_swap(cpu, opcode_info):
    """SWAP - Swap upper and lower nibbles."""
    operand = cpu.operand_values[0]
    value = _read_target(cpu, operand)
    result = ((value & 0x0F) << 4) | ((value & 0xF0) >> 4)
    _write_target(cpu, operand, result)
    cpu.set_flag('Z', result == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', False)
    cpu.set_flag('C', False)
    return opcode_info['cycles'][0]


# --- Bit operations ---

def cb_bit(cpu, opcode_info):
    """BIT n - Test bit n. Z flag set if bit is 0."""
    bit_num = int(cpu.operand_values[0]["name"])
    operand = cpu.operand_values[1]
    value = _read_target(cpu, operand)
    cpu.set_flag('Z', (value & (1 << bit_num)) == 0)
    cpu.set_flag('N', False)
    cpu.set_flag('H', True)
    # C flag unchanged
    return opcode_info['cycles'][0]


def cb_res(cpu, opcode_info):
    """RES n - Reset (clear) bit n."""
    bit_num = int(cpu.operand_values[0]["name"])
    operand = cpu.operand_values[1]
    value = _read_target(cpu, operand)
    result = value & ~(1 << bit_num)
    _write_target(cpu, operand, result)
    return opcode_info['cycles'][0]


def cb_set(cpu, opcode_info):
    """SET n - Set bit n."""
    bit_num = int(cpu.operand_values[0]["name"])
    operand = cpu.operand_values[1]
    value = _read_target(cpu, operand)
    result = value | (1 << bit_num)
    _write_target(cpu, operand, result)
    return opcode_info['cycles'][0]


# --- Dispatch table generation ---

def build_cb_dispatch():
    """Build the 256-entry CB opcode dispatch table.

    Layout:
      0x00-0x07: RLC    0x08-0x0F: RRC    0x10-0x17: RL     0x18-0x1F: RR
      0x20-0x27: SLA    0x28-0x2F: SRA    0x30-0x37: SWAP   0x38-0x3F: SRL
      0x40-0x7F: BIT    0x80-0xBF: RES    0xC0-0xFF: SET
    """
    table = {}
    rotate_shift_ops = [cb_rlc, cb_rrc, cb_rl, cb_rr, cb_sla, cb_sra, cb_swap, cb_srl]
    for op_idx, handler in enumerate(rotate_shift_ops):
        for target_idx in range(8):
            table[op_idx * 8 + target_idx] = handler
    for i in range(64):
        table[0x40 + i] = cb_bit
    for i in range(64):
        table[0x80 + i] = cb_res
    for i in range(64):
        table[0xC0 + i] = cb_set
    return table
